package com.example.core.localization

enum class AppLanguage(val code: String, val displayNameAr: String, val displayNameEn: String) {
    ARABIC("ar", "العربية", "Arabic"),
    ENGLISH("en", "English", "English")
}

data class AppStrings(
    val appName: String,
    val appSlogan: String,
    val platformTitle: String,
    val platformSubtitle: String,
    
    // Theme & Language
    val language: String,
    val darkMode: String,
    val lightMode: String,
    val arabic: String,
    val english: String,
    
    // Auth & Roles
    val login: String,
    val register: String,
    val logout: String,
    val student: String,
    val teacher: String,
    val supervisor: String,
    val teacherOrSupervisor: String,
    val loginAsStudent: String,
    val loginAsTeacherOrSupervisor: String,
    val registerAsStudent: String,
    val registerAsTeacher: String,
    val registerAsSupervisor: String,
    
    // Role Descriptions
    val studentRoleDesc: String,
    val teacherRoleDesc: String,
    
    // Form fields
    val fullName: String,
    val email: String,
    val password: String,
    val confirmPassword: String,
    val phoneNumber: String,
    val parentPhoneNumber: String,
    val teacherCode: String,
    val addTeacherCode: String,
    val removeTeacherCode: String,
    val teacherCodesTitle: String,
    val teacherCodeExample: String,
    val myCustomCode: String,
    val myCustomCodeDesc: String,
    
    // Auth actions
    val forgotPassword: String,
    val resetPassword: String,
    val sendResetLink: String,
    val backToLogin: String,
    val alreadyHaveAccount: String,
    val dontHaveAccount: String,
    val emailVerificationTitle: String,
    val emailVerificationDesc: String,
    val resendVerificationEmail: String,
    val checkVerificationStatus: String,
    val verificationSentSuccess: String,
    
    // Errors
    val errorEmptyFields: String,
    val errorInvalidEmail: String,
    val errorPasswordMismatch: String,
    val errorShortPassword: String,
    val errorInvalidPhone: String,
    val errorTeacherCodeRequired: String,
    val errorInvalidTeacherCode: String,
    val errorLoginFailed: String,
    val errorEmailNotVerified: String,
    val errorUserCodeTaken: String,
    
    // Student Dashboard
    val studentWelcome: String,
    val studentGroupSubtitle: String,
    val attendanceRate: String,
    val averageScore: String,
    val todayLessonsCount: String,
    val totalAttendance: String,
    val totalAbsence: String,
    val qrAttendanceTitle: String,
    val qrAttendanceDesc: String,
    val scanQrButton: String,
    val todayLessons: String,
    val viewFullSchedule: String,
    val recentGrades: String,
    val viewAllGrades: String,
    val scoreOutOfHundred: String,
    val statusUpcoming: String,
    val statusCompleted: String,
    
    // Teacher Dashboard
    val teacherWelcome: String,
    val teacherActivitySummary: String,
    val upcomingExams: String,
    val averageAttendance: String,
    val totalStudents: String,
    val scheduledLessonsToday: String,
    val mainOptions: String,
    val groups: String,
    val groupsDesc: String,
    val students: String,
    val studentsDesc: String,
    val exams: String,
    val examsDesc: String,
    val attendance: String,
    val attendanceDesc: String,
    val grades: String,
    val gradesDesc: String,
    val generateQr: String,
    val generateQrDesc: String,
    val reports: String,
    val messages: String,
    val settings: String,
    val createNewLesson: String,
    val studentsCountUnit: String,
    
    // Navigation items
    val home: String,
    val myResults: String,
    val myAttendance: String,
    val myAccount: String,
    val myLessons: String,
    val myWarnings: String,
    val myGroups: String,
    val myExams: String,
    val more: String,
    val aboutApp: String,
    val techSupport: String,
    val privacy: String,
    val help: String,
    val notifications: String,
    
    // Phase 2 Interactive Modules Strings
    val addGroup: String,
    val groupName: String,
    val gradeLevel: String,
    val scheduleDays: String,
    val maxStudents: String,
    val createGroupSuccess: String,
    val addStudent: String,
    val searchStudentsPlaceholder: String,
    val filterAllGroups: String,
    val callParent: String,
    val whatsappParent: String,
    val sendWarning: String,
    val warningReason: String,
    val warningSeverity: String,
    val severityLow: String,
    val severityMedium: String,
    val severityHigh: String,
    val warningSentSuccess: String,
    val createExam: String,
    val examTitle: String,
    val maxMarks: String,
    val enterGrades: String,
    val saveGrades: String,
    val gradesSavedSuccess: String,
    val markAttendance: String,
    val statusPresent: String,
    val statusAbsent: String,
    val statusLate: String,
    val statusExcused: String,
    val markAllPresent: String,
    val attendanceSavedSuccess: String,
    val search: String,
    val cancel: String,
    val save: String,
    val delete: String,
    val edit: String,
    val details: String,
    val noDataFound: String,

    // Phase 3 Analytics, Reports & QR Printing Strings
    val analyticsAndReports: String,
    val printQrCode: String,
    val printQrPoster: String,
    val exportPdf: String,
    val shareReport: String,
    val print: String,
    val performanceTrend: String,
    val gradeDistribution: String,
    val attendanceRateChart: String,
    val topStudents: String,
    val studentRank: String,
    val gradeSheet: String,
    val studentReportCard: String,
    val monthlyAttendanceReport: String,
    val excellent: String,
    val veryGood: String,
    val good: String,
    val needsImprovement: String,
    val generatePoster: String,
    val posterInstructions: String,
    val posterScanGuide: String,
    val sessionSecurityCode: String,
    val roomHall: String,
    val shareWhatsApp: String,
    val reportGeneratedDate: String,
    val teacherEvaluation: String,
    val cumulativeAttendance: String,
    val examsTaken: String,
    val averageGradePercent: String
)

object LocalizedStrings {
    val Arabic = AppStrings(
        appName = "Educore",
        appSlogan = "التطبيق الأمثل للإدارة",
        platformTitle = "Educore",
        platformSubtitle = "منصة متكاملة لإدارة طلابك ومتابعة أدائهم بسهولة واحترافية",
        language = "اللغة",
        darkMode = "الوضع الداكن",
        lightMode = "الوضع الفاتح",
        arabic = "العربية",
        english = "English",
        login = "تسجيل الدخول",
        register = "إنشاء حساب جديد",
        logout = "تسجيل الخروج",
        student = "طالب",
        teacher = "أستاذ / معلم",
        supervisor = "مشرف",
        teacherOrSupervisor = "أستاذ / مشرف",
        loginAsStudent = "دخول كطالب",
        loginAsTeacherOrSupervisor = "دخول كأستاذ",
        registerAsStudent = "تسجيل حساب طالب جديد",
        registerAsTeacher = "تسجيل كمعلم جديد",
        registerAsSupervisor = "تسجيل كمشرف جديد",
        studentRoleDesc = "مسح QR لتسجيل الحضور، عرض الدرجات ومتابعة الحصص والامتحانات",
        teacherRoleDesc = "إدارة المجموعات والطلاب، الحضور والدرجات، الامتحانات والتقارير",
        fullName = "الاسم الكامل",
        email = "البريد الإلكتروني",
        password = "كلمة المرور",
        confirmPassword = "تأكيد كلمة المرور",
        phoneNumber = "رقم الهاتف الشخصي",
        parentPhoneNumber = "رقم هاتف ولي الأمر",
        teacherCode = "كود المعلم",
        addTeacherCode = "+ إضافة كود معلم آخر",
        removeTeacherCode = "حذف الكود",
        teacherCodesTitle = "أكواد المعلمين المرتبطين",
        teacherCodeExample = "مثال: mahmoud123 أو BIO-2025",
        myCustomCode = "الكود التعريفي الخاص بك",
        myCustomCodeDesc = "كود فريد يتيح للطلاب الانضمام إليك (مثال: mahmoud123)",
        forgotPassword = "هل نسيت كلمة المرور؟",
        resetPassword = "إعادة تعيين كلمة المرور",
        sendResetLink = "إرسال رابط إعادة التعيين",
        backToLogin = "العودة لتسجيل الدخول",
        alreadyHaveAccount = "لديك حساب بالفعل؟ تسجيل الدخول",
        dontHaveAccount = "ليس لديك حساب؟ إنشاء حساب جديد",
        emailVerificationTitle = "تأكيد البريد الإلكتروني",
        emailVerificationDesc = "تم إرسال رابط تأكيد الحساب إلى بريدك الإلكتروني. يرجى الضغط على الرابط لتفعيل حسابك ومتابعة الاستخدام.",
        resendVerificationEmail = "إعادة إرسال البريد",
        checkVerificationStatus = "التحقق من حالة التفعيل",
        verificationSentSuccess = "تم إرسال رابط التفعيل بنجاح إلى بريدك الإلكتروني",
        errorEmptyFields = "يرجى ملء جميع الحقول المطلوبة",
        errorInvalidEmail = "يرجى إدخال بريد إلكتروني صالح",
        errorPasswordMismatch = "كلمتا المرور غير متطابقتين",
        errorShortPassword = "كلمة المرور يجب ألا تقل عن 6 أحرف",
        errorInvalidPhone = "يرجى إدخال رقم هاتف صحيح",
        errorTeacherCodeRequired = "يجب إدخال كود معلم واحد على الأقل",
        errorInvalidTeacherCode = "كود المعلم غير صحيح أو غير موجود",
        errorLoginFailed = "بيانات تسجيل الدخول غير صحيحة، يرجى المحاولة ثانية",
        errorEmailNotVerified = "لم يتم تأكيد البريد الإلكتروني بعد، يرجى تفعيله أولاً",
        errorUserCodeTaken = "هذا الكود مستخدم بالفعل، يرجى اختيار كود آخر",
        studentWelcome = "مرحباً بك",
        studentGroupSubtitle = "طالب في مجموعة ثالثة ثانوي (أ)",
        attendanceRate = "نسبة الحضور",
        averageScore = "متوسط الدرجات",
        todayLessonsCount = "حصص اليوم",
        totalAttendance = "إجمالي الحضور",
        totalAbsence = "إجمالي الغياب",
        qrAttendanceTitle = "تسجيل الحضور",
        qrAttendanceDesc = "امسح رمز QR الخاص بالحصة لتسجيل حضورك الفوري",
        scanQrButton = "مسح QR",
        todayLessons = "حصص اليوم",
        viewFullSchedule = "عرض الجدول الكامل",
        recentGrades = "أحدث الدرجات",
        viewAllGrades = "عرض كل الدرجات",
        scoreOutOfHundred = "من 100",
        statusUpcoming = "قادمة",
        statusCompleted = "منتهية",
        teacherWelcome = "مرحباً بك أستاذ",
        teacherActivitySummary = "إليك ملخص نشاطك التعليمي اليومي",
        upcomingExams = "الامتحانات القادمة",
        averageAttendance = "متوسط الحضور",
        totalStudents = "إجمالي الطلاب",
        scheduledLessonsToday = "حصص اليوم المجدولة",
        mainOptions = "الخيارات الرئيسية",
        groups = "المجموعات",
        groupsDesc = "إدارة جميع المجموعات والفصول",
        students = "الطلاب",
        studentsDesc = "إدارة بيانات الطلاب والحسابات",
        exams = "الامتحانات",
        examsDesc = "إنشاء وإدارة الامتحانات والجداول",
        attendance = "الحضور",
        attendanceDesc = "متابعة الحضور والغياب للحصص",
        grades = "الدرجات",
        gradesDesc = "إدارة الدرجات والنتائج والتقارير",
        generateQr = "توليد QR الحصة",
        generateQrDesc = "إنشاء رمز QR لحصة جديدة ومشاركته",
        reports = "التقارير",
        messages = "الرسائل",
        settings = "الإعدادات",
        createNewLesson = "+ إنشاء حصة جديدة",
        studentsCountUnit = "طالب",
        home = "الرئيسية",
        myResults = "نتائجي",
        myAttendance = "حضوري",
        myAccount = "حسابي",
        myLessons = "حصصي",
        myWarnings = "إنذارات",
        myGroups = "مجموعاتي",
        myExams = "امتحاناتي",
        more = "المزيد",
        aboutApp = "عن التطبيق",
        techSupport = "الدعم الفني",
        privacy = "الخصوصية",
        help = "مساعدة",
        notifications = "إشعارات",
        
        // Phase 2 translations Ar
        addGroup = "+ إضافة مجموعة جديدة",
        groupName = "اسم المجموعة",
        gradeLevel = "المرحلة الدراسية",
        scheduleDays = "أيام ومواعيد الحصص",
        maxStudents = "السعة القصوى للطلاب",
        createGroupSuccess = "تم إنشاء المجموعة بنجاح",
        addStudent = "+ إضافة طالب جديد",
        searchStudentsPlaceholder = "بحث باسم الطالب أو الهاتف...",
        filterAllGroups = "جميع المجموعات",
        callParent = "اتصال بولي الأمر",
        whatsappParent = "واتساب ولي الأمر",
        sendWarning = "إصدار إنذار / ملاحظة",
        warningReason = "سبب الإنذار أو الملاحظة",
        warningSeverity = "درجة الإنذار",
        severityLow = "تنبيه خفيف",
        severityMedium = "إنذار متوسط",
        severityHigh = "إنذار شديد",
        warningSentSuccess = "تم تسجيل الإنذار وإشعار ولي الأمر بنجاح",
        createExam = "+ إنشاء امتحان جديد",
        examTitle = "عنوان الامتحان",
        maxMarks = "الدرجة العظمى",
        enterGrades = "رصد الدرجات",
        saveGrades = "حفظ وتثبيت الدرجات",
        gradesSavedSuccess = "تم رصد وحفظ الدرجات بنجاح",
        markAttendance = "تسجيل الحضور اليدوي",
        statusPresent = "حاضر",
        statusAbsent = "غائب",
        statusLate = "متأخر",
        statusExcused = "معذور",
        markAllPresent = "تحديد الكل حاضر",
        attendanceSavedSuccess = "تم حفظ سجل الحضور بنجاح",
        search = "بحث",
        cancel = "إلغاء",
        save = "حفظ",
        delete = "حذف",
        edit = "تعديل",
        details = "التفاصيل",
        noDataFound = "لا توجد بيانات متاحة حالياً",

        // Phase 3 Arabic
        analyticsAndReports = "التحليلات والتقارير",
        printQrCode = "طباعة كود الحضور",
        printQrPoster = "طباعة بوستر الحضور للقاعة",
        exportPdf = "تصدير وطباعة التقرير",
        shareReport = "مشاركة التقرير",
        print = "طباعة",
        performanceTrend = "مؤشر الأداء والدرجات",
        gradeDistribution = "توزيع التقديرات",
        attendanceRateChart = "نسبة الحضور والغياب",
        topStudents = "لوحة الشرف والمتفوقين",
        studentRank = "الترتيب",
        gradeSheet = "كشف درجات تفصيلي",
        studentReportCard = "بطاقة تقييم الطالب الشاملة",
        monthlyAttendanceReport = "تقرير الحضور الشهري",
        excellent = "ممتاز (90%+)",
        veryGood = "جيد جداً (75-89%)",
        good = "جيد (60-74%)",
        needsImprovement = "يحتاج متابعة (<60%)",
        generatePoster = "إنشاء وتخصيص البوستر",
        posterInstructions = "إرشادات مسح الرمز",
        posterScanGuide = "افتح تطبيق Educore وقم بمسح هذا الرمز لتسجيل حضورك الفوري في الحصة الدراسية",
        sessionSecurityCode = "رمز الجلسة الأمني",
        roomHall = "القاعة / الفصل",
        shareWhatsApp = "مشاركة عبر واتساب",
        reportGeneratedDate = "تاريخ إصدار التقرير",
        teacherEvaluation = "التقييم العام للمستوى",
        cumulativeAttendance = "نسبة الحضور الإجمالية",
        examsTaken = "الاختبارات المنجزة",
        averageGradePercent = "المعدل التراكمي"
    )

    val English = AppStrings(
        appName = "Educore",
        appSlogan = "The Ultimate Management System",
        platformTitle = "Educore Platform",
        platformSubtitle = "A comprehensive platform to manage students and track performance with ease and elegance",
        language = "Language",
        darkMode = "Dark Mode",
        lightMode = "Light Mode",
        arabic = "العربية",
        english = "English",
        login = "Log In",
        register = "Create Account",
        logout = "Log Out",
        student = "Student",
        teacher = "Teacher",
        supervisor = "Supervisor",
        teacherOrSupervisor = "Teacher / Supervisor",
        loginAsStudent = "Student Login",
        loginAsTeacherOrSupervisor = "Teacher Login",
        registerAsStudent = "Register as Student",
        registerAsTeacher = "Register as Teacher",
        registerAsSupervisor = "Register as Supervisor",
        studentRoleDesc = "Scan QR for attendance, view grades, lessons, and secure exams",
        teacherRoleDesc = "Manage groups, student rosters, QR attendance, and reports",
        fullName = "Full Name",
        email = "Email Address",
        password = "Password",
        confirmPassword = "Confirm Password",
        phoneNumber = "Personal Phone Number",
        parentPhoneNumber = "Parent Phone Number",
        teacherCode = "Teacher Code",
        addTeacherCode = "+ Add Another Teacher Code",
        removeTeacherCode = "Remove",
        teacherCodesTitle = "Associated Teacher Codes",
        teacherCodeExample = "e.g., mahmoud123 or BIO-2025",
        myCustomCode = "Your Custom Teacher Code",
        myCustomCodeDesc = "A unique code that lets your students find and join you",
        forgotPassword = "Forgot Password?",
        resetPassword = "Reset Password",
        sendResetLink = "Send Reset Link",
        backToLogin = "Back to Login",
        alreadyHaveAccount = "Already have an account? Log In",
        dontHaveAccount = "Don't have an account? Sign Up",
        emailVerificationTitle = "Email Verification",
        emailVerificationDesc = "A verification link has been sent to your email. Please verify to activate your account and continue.",
        resendVerificationEmail = "Resend Email",
        checkVerificationStatus = "Check Status",
        verificationSentSuccess = "Verification link sent successfully to your email",
        errorEmptyFields = "Please fill in all required fields",
        errorInvalidEmail = "Please enter a valid email address",
        errorPasswordMismatch = "Passwords do not match",
        errorShortPassword = "Password must be at least 6 characters",
        errorInvalidPhone = "Please enter a valid phone number",
        errorTeacherCodeRequired = "At least one teacher code is required",
        errorInvalidTeacherCode = "Teacher code is invalid or not found",
        errorLoginFailed = "Invalid credentials. Please try again.",
        errorEmailNotVerified = "Email is not verified yet. Please verify your email.",
        errorUserCodeTaken = "This code is already taken. Please choose another one.",
        studentWelcome = "Welcome",
        studentGroupSubtitle = "Student in Group 3rd Secondary (A)",
        attendanceRate = "Attendance Rate",
        averageScore = "Average Score",
        todayLessonsCount = "Today's Lessons",
        totalAttendance = "Total Present",
        totalAbsence = "Total Absent",
        qrAttendanceTitle = "QR Attendance",
        qrAttendanceDesc = "Scan the active session QR code to record your instant attendance",
        scanQrButton = "Scan QR",
        todayLessons = "Today's Lessons",
        viewFullSchedule = "View Full Schedule",
        recentGrades = "Recent Grades",
        viewAllGrades = "View All Grades",
        scoreOutOfHundred = "out of 100",
        statusUpcoming = "Upcoming",
        statusCompleted = "Completed",
        teacherWelcome = "Welcome Teacher",
        teacherActivitySummary = "Here is your daily teaching activity summary",
        upcomingExams = "Upcoming Exams",
        averageAttendance = "Avg Attendance",
        totalStudents = "Total Students",
        scheduledLessonsToday = "Scheduled Lessons",
        mainOptions = "Main Options",
        groups = "Groups",
        groupsDesc = "Manage all batches and classrooms",
        students = "Students",
        studentsDesc = "Manage student profiles and rosters",
        exams = "Exams",
        examsDesc = "Create & grade online or offline exams",
        attendance = "Attendance",
        attendanceDesc = "Track attendance per lesson and group",
        grades = "Grades",
        gradesDesc = "Manage test scores, ranks, and reports",
        generateQr = "Generate Session QR",
        generateQrDesc = "Create and share live QR codes for lessons",
        reports = "Reports",
        messages = "Messages",
        settings = "Settings",
        createNewLesson = "+ Create New Lesson",
        studentsCountUnit = "Students",
        home = "Home",
        myResults = "My Results",
        myAttendance = "My Attendance",
        myAccount = "My Account",
        myLessons = "My Lessons",
        myWarnings = "Warnings",
        myGroups = "My Groups",
        myExams = "My Exams",
        more = "More",
        aboutApp = "About App",
        techSupport = "Tech Support",
        privacy = "Privacy",
        help = "Help",
        notifications = "Notifications",
        
        // Phase 2 translations En
        addGroup = "+ Add New Group",
        groupName = "Group Name",
        gradeLevel = "Grade Level",
        scheduleDays = "Schedule & Days",
        maxStudents = "Max Students Capacity",
        createGroupSuccess = "Group created successfully",
        addStudent = "+ Add New Student",
        searchStudentsPlaceholder = "Search by student name or phone...",
        filterAllGroups = "All Groups",
        callParent = "Call Parent",
        whatsappParent = "WhatsApp Parent",
        sendWarning = "Issue Warning / Notice",
        warningReason = "Warning Reason / Note",
        warningSeverity = "Severity Level",
        severityLow = "Notice",
        severityMedium = "Warning",
        severityHigh = "Critical",
        warningSentSuccess = "Warning registered and parent notified",
        createExam = "+ Create New Exam",
        examTitle = "Exam Title",
        maxMarks = "Maximum Marks",
        enterGrades = "Enter Grades",
        saveGrades = "Save & Post Grades",
        gradesSavedSuccess = "Grades saved successfully",
        markAttendance = "Manual Attendance",
        statusPresent = "Present",
        statusAbsent = "Absent",
        statusLate = "Late",
        statusExcused = "Excused",
        markAllPresent = "Mark All Present",
        attendanceSavedSuccess = "Attendance record saved successfully",
        search = "Search",
        cancel = "Cancel",
        save = "Save",
        delete = "Delete",
        edit = "Edit",
        details = "Details",
        noDataFound = "No data available at this time",

        // Phase 3 English
        analyticsAndReports = "Analytics & Reports",
        printQrCode = "Print Attendance QR",
        printQrPoster = "Print Hall QR Poster",
        exportPdf = "Export & Print Report",
        shareReport = "Share Report",
        print = "Print",
        performanceTrend = "Performance & Score Trends",
        gradeDistribution = "Grade Distribution",
        attendanceRateChart = "Attendance & Absence Rate",
        topStudents = "Honor Roll & Top Students",
        studentRank = "Rank",
        gradeSheet = "Detailed Grade Sheet",
        studentReportCard = "Comprehensive Student Report Card",
        monthlyAttendanceReport = "Monthly Attendance Report",
        excellent = "Excellent (90%+)",
        veryGood = "Very Good (75-89%)",
        good = "Good (60-74%)",
        needsImprovement = "Needs Support (<60%)",
        generatePoster = "Generate & Customize Poster",
        posterInstructions = "Scanning Instructions",
        posterScanGuide = "Open the Educore app and scan this code to register your real-time attendance in class",
        sessionSecurityCode = "Session Security Code",
        roomHall = "Room / Hall",
        shareWhatsApp = "Share via WhatsApp",
        reportGeneratedDate = "Report Issue Date",
        teacherEvaluation = "Overall Performance Rating",
        cumulativeAttendance = "Cumulative Attendance Rate",
        examsTaken = "Exams Completed",
        averageGradePercent = "Cumulative GPA / Average"
    )

    fun get(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.ARABIC -> Arabic
            AppLanguage.ENGLISH -> English
        }
    }
}
